# Generated by Django 5.2.10 on 2026-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_type',
            field=models.CharField(choices=[('airport', 'Airport Drop-off'), ('6h', '6 Hours'), ('12h', '12 Hours'), ('custom', 'Custom')], default='airport', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
