# Generated by Django 5.2.10 on 2026-01-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_booking_destination_booking_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
