# Generated by Django 5.2.10 on 2026-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_booking_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration_type',
            field=models.CharField(choices=[('airport', 'Airport Drop-off'), ('6h', '6 Hours'), ('12h', '12 Hours')], default='airport', max_length=20),
        ),
    ]
