# Generated by Django 5.2.10 on 2026-01-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_booking_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration_type',
            field=models.CharField(choices=[('airport', 'Airport Drop-off'), ('airport', 'Airport Pick-up'), ('10h', '10 Hours'), ('12h', '12 Hours'), ('custom', 'Select Return Date')], default='airport', max_length=20),
        ),
    ]
